const dummyData = [
    {   id: 1, 
        name: 'Item One', 
        quantity: 4, 
        price: 9.99, 
        onSale:false,
        category: "Summer",
        img: 'https://images.unsplash.com/photo-1526930382372-67bf22c0fce2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet arcu vel magna semper tincidunt. In condimentum consectetur sem quis fringilla. Mauris nec nisi ac turpis lacinia aliquam sit amet consequat nisl. Vestibulum eget urna vestibulum, porttitor dui id, euismod lectus. Praesent aliquet convallis auctor. Nullam dignissim pellentesque ipsum, nec sodales elit mattis eu. Ut venenatis ac augue eget dignissim. Donec commodo rutrum quam. Pellentesque viverra lectus eu nisl vestibulum vulputate. In eget velit vel turpis bibendum feugiat ut id velit. Sed eu sapien urna. Nullam nec erat eu mauris eleifend molestie nec venenatis dui. Vestibulum elementum a metus eu lobortis. Ut hendrerit lorem aliquet augue mattis, non fringilla mauris iaculis. Mauris vitae porttitor erat. Phasellus dignissim diam eget est eleifend varius. Quisque faucibus feugiat nisl, id sollicitudin ante mollis in. Donec hendrerit arcu ut porttitor tempus. Quisque fringilla metus a lectus suscipit fringilla. Vivamus facilisis congue tristique. Morbi.'
    },
    {   id: 2, 
        name: 'Item Two', 
        quantity: 3, 
        price: 199.99, 
        onSale:false,
        category: "Fall",
        img: 'https://images.unsplash.com/photo-1557906757-541777a3e36b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', 
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet sem eu augue congue dapibus nec et magna. Nam nec ante luctus, dignissim eros vel, accumsan tortor. Donec et lorem nisi. Donec id lorem elit. Morbi volutpat lacus sapien, ut ornare lorem consectetur at. Curabitur sollicitudin, magna eu consequat mollis, leo ex scelerisque orci, vitae ornare justo lectus ut mi. Suspendisse tincidunt mi vitae finibus placerat. In euismod, erat et vehicula luctus, lacus dolor pellentesque purus, id gravida odio leo ac elit. Pellentesque justo ligula, gravida ac metus sagittis, finibus vulputate enim. Aenean non facilisis mi. Fusce vitae diam justo. Aliquam varius ipsum ligula, ac egestas mauris accumsan vel. Vestibulum vitae erat nisi. Praesent euismod rhoncus dolor, nec accumsan arcu luctus et. Pellentesque sit amet massa non velit pretium ultricies id nec ligula. Sed molestie elementum massa a ullamcorper. Aenean suscipit, augue nec sollicitudin commodo, massa velit aliquam eros, eget mollis magna arcu ac magna. Sed egestas ex et nunc ornare tristique. Etiam elementum libero ac lobortis blandit. Duis vehicula leo non quam gravida, a mattis nisl placerat. Fusce sit amet aliquet est. Aliquam euismod tincidunt viverra. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
    },
    {   id: 3, 
        name: 'Item Three', 
        quantity: 11, 
        price: 17.99, 
        onSale:true,
        category: "Winter",
        img: 'https://images.unsplash.com/photo-1623044584823-4949db1b1a9a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pretium odio at sapien pharetra, ut vulputate lorem convallis. Sed suscipit dui est, et blandit felis molestie et. Aenean tincidunt, orci id faucibus eleifend, purus orci condimentum turpis, vitae hendrerit felis turpis et libero. Vestibulum ut consectetur nisi, eget fringilla mi. Mauris condimentum mi in enim dapibus, a molestie nisi luctus. Mauris gravida leo at tincidunt venenatis. Vestibulum laoreet, orci quis sollicitudin congue, odio est molestie velit, non maximus nisi felis sed lectus. In nibh metus, viverra eget tristique at, viverra vel neque. In varius orci vitae tortor accumsan laoreet. Sed vulputate odio sit amet lacus pharetra porttitor. Nunc hendrerit sodales urna, et congue nunc viverra at. Nulla est arcu, blandit quis rutrum et, rhoncus sit amet massa. Donec scelerisque cursus arcu, vel tempor nibh faucibus eu. Praesent ut leo lorem. Aliquam dictum ultrices ultricies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean enim turpis, dignissim id urna sit amet, tincidunt venenatis lorem. Sed at dui sit amet mauris viverra rhoncus. Vivamus iaculis elit odio, a sodales sapien dapibus in. Mauris metus lectus, dapibus tristique cursus ac, porttitor non neque. Praesent sit amet euismod lacus. Vestibulum a augue volutpat, tempor justo sit amet, placerat arcu. Ut facilisis sodales erat. Nam dolor arcu, porttitor et nisi vel, consectetur sodales purus. Phasellus nec vestibulum ex. Vivamus in luctus magna, sed egestas ipsum. Pellentesque rutrum neque lacus, nec tincidunt turpis venenatis nec. Integer felis elit, gravida ut tincidunt eget, vestibulum at ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer lorem erat, laoreet vel lectus sed, iaculis iaculis felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean varius porttitor lacus, sit amet rhoncus enim mattis quis. Duis sed ligula dictum est.'
    },
    {   id: 4, 
        name: 'Item Four', 
        quantity: 0, 
        price: 0.99, 
        onSale:true,
        category: "Spring",
        img: 'https://images.unsplash.com/photo-1622586757007-efda9475c347?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris rutrum dui aliquet consequat commodo. Vivamus ac urna molestie, accumsan sapien sed, pharetra est. Mauris aliquet laoreet congue. Sed dignissim, tortor et lobortis lobortis, sem turpis blandit nunc, quis pretium justo est at purus. Quisque eget suscipit enim. Nullam scelerisque leo ac tincidunt porta. Aenean egestas urna nec ipsum sagittis, nec mattis erat tincidunt. Vivamus quis facilisis nibh, eu sagittis nunc. Phasellus nec semper metus. Integer aliquet neque vel metus porttitor, eget aliquet metus sagittis. Nullam ut est ac lorem tincidunt aliquet. Sed leo libero, venenatis ut feugiat in, ornare eget erat. Morbi id est risus. Curabitur sollicitudin tortor ac nulla rhoncus placerat. Curabitur eget ultricies nisl, non semper neque. Nulla euismod, lectus quis posuere rutrum, leo neque pulvinar ipsum, et consequat sapien eros vitae neque. Aenean vitae finibus purus. Curabitur egestas accumsan lorem. Phasellus ut felis lectus. Nam ut sem eget est molestie gravida a eu augue. Praesent condimentum nibh dolor. Aliquam lectus mi, vulputate sit amet velit non, convallis cursus ex. Fusce varius rutrum.'
    },
    {   id: 5, 
        name: 'Item Five', 
        quantity: 5, 
        price: 88.99, 
        onSale:false,
        category: "Summer",
        img: 'https://images.unsplash.com/photo-1572721546624-05bf65ad7679?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=966&q=80',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec posuere iaculis leo id aliquet. Integer scelerisque egestas justo, eget commodo lectus lacinia non. Proin porttitor euismod nibh, lobortis ornare ex convallis sed. Etiam ut scelerisque tortor, et egestas nunc. Nulla eget placerat ex. Ut quis nisi vehicula, tristique est et, sagittis dui. Aenean maximus eros vitae condimentum laoreet. Nulla porttitor, eros in egestas congue, magna tortor placerat mauris, vitae condimentum purus nisi non odio. In hac habitasse platea dictumst. Praesent commodo, magna vel accumsan consequat, erat sem ultrices urna, blandit imperdiet enim turpis ac nisl. Sed in lacus pulvinar, elementum justo eget, feugiat justo. Fusce semper, lorem vel mattis eleifend, justo mi tincidunt augue, vitae dignissim eros odio sed libero. Fusce ut mauris eget diam.'
    },
    {   id: 6, 
        name: 'Item Six', 
        quantity: 17, 
        price: 109.99, 
        onSale:false,
        category: "Spring",
        img: 'https://images.unsplash.com/photo-1579002817436-c43abe408364?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=666&q=80',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultrices ultrices felis a semper. Aliquam sit amet enim egestas, iaculis lacus vel, aliquam ligula. Cras ultricies molestie quam non tincidunt. Aenean eget malesuada dolor. Vestibulum quis imperdiet risus. Praesent aliquet massa vitae ligula fermentum, nec lobortis nibh tempor. Integer quis magna est. Vivamus tortor mauris, pharetra quis lacinia id, condimentum quis lectus. Curabitur aliquet massa ac erat dapibus, pellentesque luctus nibh congue. Morbi condimentum hendrerit lorem at dictum. Duis finibus sed orci a sollicitudin. Phasellus at urna pulvinar, laoreet purus vel, ultrices lacus. Nulla blandit velit ut odio interdum, ut congue nulla fringilla. Aenean turpis ante, lacinia sit amet neque ut, ultricies ultrices ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras nec sapien ante. Duis scelerisque ex sapien, auctor mattis arcu malesuada sit amet. Aliquam erat volutpat. Pellentesque dui nibh, ultricies quis risus ultricies, molestie ullamcorper diam. Curabitur fringilla elit vel tellus ultricies, dignissim malesuada tortor semper. Duis et quam auctor, dapibus sem quis, luctus metus. Ut sed venenatis risus, quis vehicula magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque vel bibendum ante, at porttitor eros. Proin quis sem eget elit dapibus accumsan. Aliquam ultricies nisi sed suscipit vehicula. Ut maximus tortor dapibus nunc aliquet cursus. Duis ut metus vel sapien bibendum congue vel eu diam. In vel fermentum augue. Suspendisse velit ex, tincidunt scelerisque elit non, mollis euismod est. Morbi elementum odio vitae odio laoreet blandit. Etiam cursus leo turpis. Praesent nunc massa, bibendum non est et, consequat mattis nisl. Praesent enim erat, efficitur tempor pharetra eu, luctus id nisl. In eu mauris efficitur, rhoncus nisi nec, dictum quam. Sed luctus sit amet dui non molestie. Nulla aliquet consectetur porta. Proin bibendum diam non massa.'
    },
]

export default dummyData;